// Curated community catalog extension for CaseyCZ Scriptable Apps.
// Original code remains hosted by the original authors. This file stores metadata only.
const communityItem=(name,category,author,icon,file,filename,source,preview,tags,cs,en)=>({
  name,category,author,icon,file,filename,source,preview,tags,
  description:{cs,en},
  features:{
    cs:['Původní open-source projekt','Stahování přímo od autora','Nastavení a požadavky v dokumentaci autora'],
    en:['Original open-source project','Direct download from the author','Setup and requirements in the author documentation']
  }
});

window.communityExtraApps=[
// yaylinda — 7
communityItem('Calendar Events Widget','calendar','yaylinda','📆','https://raw.githubusercontent.com/yaylinda/scriptable/main/CalendarEventsWidget.js','CalendarEventsWidget.js','https://github.com/yaylinda/scriptable','https://raw.githubusercontent.com/yaylinda/scriptable/main/images/CalendarEventsWidget.png',['Calendar','Events'],'Přehled nejbližších událostí z kalendáře.','Upcoming calendar events in a clean widget.'),
communityItem('Multi-Day Calendar','calendar','yaylinda','🗓️','https://raw.githubusercontent.com/yaylinda/scriptable/main/MultiDayCalendarWidget.js','MultiDayCalendarWidget.js','https://github.com/yaylinda/scriptable','https://raw.githubusercontent.com/yaylinda/scriptable/main/images/MultiDayCalendarWidget.png',['Calendar','Multi-day'],'Vícedenní kalendářní přehled na ploše.','Multi-day calendar overview for the Home Screen.'),
communityItem('Daily Log Widget','tools','yaylinda','📝','https://raw.githubusercontent.com/yaylinda/scriptable/main/DailyLogWidget.js','DailyLogWidget.js','https://github.com/yaylinda/scriptable','https://raw.githubusercontent.com/yaylinda/scriptable/main/images/DailyLogWidget.png',['Log','Notes'],'Rychlý denní log a přehled záznamů.','Quick daily logging and entry overview.'),
communityItem('Daily Log Aggregator','tools','yaylinda','📚','https://raw.githubusercontent.com/yaylinda/scriptable/main/DailyLogAggregator.js','DailyLogAggregator.js','https://github.com/yaylinda/scriptable','https://opengraph.githubassets.com/1/yaylinda/scriptable',['Log','Archive'],'Agregace denních logů do jednoho přehledu.','Aggregates daily logs into one overview.'),
communityItem('Discord Widget','social','yaylinda','💬','https://raw.githubusercontent.com/yaylinda/scriptable/main/DiscordWidget.js','DiscordWidget.js','https://github.com/yaylinda/scriptable','https://raw.githubusercontent.com/yaylinda/scriptable/main/images/DiscordWidget.png',['Discord','Social'],'Přehled Discord informací ve widgetu.','Discord information in a Scriptable widget.'),
communityItem('Terminal Widget','tools','yaylinda','⌨️','https://raw.githubusercontent.com/yaylinda/scriptable/main/TerminalWidget.js','TerminalWidget.js','https://github.com/yaylinda/scriptable','https://raw.githubusercontent.com/yaylinda/scriptable/main/images/TerminalWidget.png',['Terminal','Developer'],'Terminálově laděný informační widget.','Terminal-styled information widget.'),
communityItem('Word Clock by yaylinda','tools','yaylinda','🕒','https://raw.githubusercontent.com/yaylinda/scriptable/main/WordClockWidget.js','WordClockWidget.js','https://github.com/yaylinda/scriptable','https://raw.githubusercontent.com/yaylinda/scriptable/main/images/WordClockWidget.png',['Clock','Typography'],'Textové hodiny v minimalistickém stylu.','Minimal word-clock widget.'),

// doersino — 7
communityItem('Aerialbot Lite','tools','doersino','🤖','https://raw.githubusercontent.com/doersino/scriptable-widgets/main/aerialbot-lite/aerialbot-lite.js','aerialbot-lite.js','https://github.com/doersino/scriptable-widgets/tree/main/aerialbot-lite','https://raw.githubusercontent.com/doersino/scriptable-widgets/main/aerialbot-lite/demo.png',['Automation','Status'],'Lehký stavový widget inspirovaný Aerialbotem.','Lightweight status widget inspired by Aerialbot.'),
communityItem('Binary Date','tools','doersino','🔢','https://raw.githubusercontent.com/doersino/scriptable-widgets/main/binary-date/binary-date.js','binary-date.js','https://github.com/doersino/scriptable-widgets/tree/main/binary-date','https://raw.githubusercontent.com/doersino/scriptable-widgets/main/binary-date/demo.jpg',['Date','Binary'],'Datum zobrazené v binárním stylu.','Date displayed in binary style.'),
communityItem('Location Location Location','travel','doersino','📍','https://raw.githubusercontent.com/doersino/scriptable-widgets/main/location-location-location/location-location-location.js','location-location-location.js','https://github.com/doersino/scriptable-widgets/tree/main/location-location-location','https://raw.githubusercontent.com/doersino/scriptable-widgets/main/location-location-location/demo.jpg',['Location','Travel'],'Widget s informacemi o aktuální poloze.','Widget with current-location information.'),
communityItem('Read Statistics','reading','doersino','📖','https://raw.githubusercontent.com/doersino/scriptable-widgets/main/read-statistics/read-statistics.js','read-statistics.js','https://github.com/doersino/scriptable-widgets/tree/main/read-statistics','https://raw.githubusercontent.com/doersino/scriptable-widgets/main/read-statistics/demo.jpg',['Reading','Statistics'],'Statistiky čtení v kompaktním widgetu.','Reading statistics in a compact widget.'),
communityItem('Small Seasons','weather','doersino','🍂','https://raw.githubusercontent.com/doersino/scriptable-widgets/main/small-seasons/small-seasons.js','small-seasons.js','https://github.com/doersino/scriptable-widgets/tree/main/small-seasons','https://raw.githubusercontent.com/doersino/scriptable-widgets/main/small-seasons/demo.jpg',['Seasons','Date'],'Minimalistický přehled ročního období.','Minimal seasonal overview.'),
communityItem('Uberspace Quota','tools','doersino','💾','https://raw.githubusercontent.com/doersino/scriptable-widgets/main/uberspace-quota/uberspace-quota.js','uberspace-quota.js','https://github.com/doersino/scriptable-widgets/tree/main/uberspace-quota','https://raw.githubusercontent.com/doersino/scriptable-widgets/main/uberspace-quota/demo.jpg',['Server','Quota'],'Využití prostoru a kvóty Uberspace.','Uberspace storage and quota usage.'),
communityItem('Weekly Cycling Distance','sport','doersino','🚴','https://raw.githubusercontent.com/doersino/scriptable-widgets/main/weekly-cycling-distance/weekly-cycling-distance.js','weekly-cycling-distance.js','https://github.com/doersino/scriptable-widgets/tree/main/weekly-cycling-distance','https://raw.githubusercontent.com/doersino/scriptable-widgets/main/weekly-cycling-distance/demo.jpg',['Cycling','Fitness'],'Týdenní cyklistická vzdálenost ve widgetu.','Weekly cycling distance in a widget.'),

// mvan231 — 26
communityItem('Alexa To Reminders','tools','mvan231','🔔','https://raw.githubusercontent.com/mvan231/Scriptable/main/Alexa%20To%20Reminders%20Access.js','Alexa To Reminders Access.js','https://github.com/mvan231/Scriptable','https://opengraph.githubassets.com/1/mvan231/Scriptable',['Alexa','Reminders'],'Propojení Alexa úkolů s Připomínkami.','Connect Alexa tasks with Reminders.'),
communityItem('Automators.fm Feed','news','mvan231','🎙️','https://raw.githubusercontent.com/mvan231/Scriptable/main/Automators.fm%20Feed/Automators.fm%20Feed%20Widget.js','Automators.fm Feed Widget.js','https://github.com/mvan231/Scriptable','https://opengraph.githubassets.com/2/mvan231/Scriptable',['Podcast','RSS'],'Widget s nejnovější epizodou Automators.fm.','Latest Automators.fm episode widget.'),
communityItem('COD Warzone Stats','gaming','mvan231','🎮','https://raw.githubusercontent.com/mvan231/Scriptable/main/COD%20Warzone%20Stats.js','COD Warzone Stats.js','https://github.com/mvan231/Scriptable','https://opengraph.githubassets.com/3/mvan231/Scriptable',['Gaming','Stats'],'Statistiky hráče Call of Duty Warzone.','Call of Duty Warzone player statistics.'),
communityItem('Circles with Image','art','mvan231','🟣','https://raw.githubusercontent.com/mvan231/Scriptable/main/Circles%20with%20image.js','Circles with image.js','https://github.com/mvan231/Scriptable','https://opengraph.githubassets.com/4/mvan231/Scriptable',['Design','Image'],'Grafický widget s kruhy a obrázkem.','Graphic widget example with circles and an image.'),
communityItem('Combine Photos Grid','tools','mvan231','🖼️','https://raw.githubusercontent.com/mvan231/Scriptable/main/Combine%20photos%20w%20grid','Combine photos grid.js','https://github.com/mvan231/Scriptable','https://opengraph.githubassets.com/5/mvan231/Scriptable',['Photos','Grid'],'Spojí fotografie do přehledné mřížky.','Combines photos into a clean grid.'),
communityItem('Dashed Line','art','mvan231','➖','https://raw.githubusercontent.com/mvan231/Scriptable/main/Dashed%20Line.js','Dashed Line.js','https://github.com/mvan231/Scriptable','https://opengraph.githubassets.com/6/mvan231/Scriptable',['Design','Drawing'],'Ukázka kreslení přerušovaných čar v Scriptable.','Example of drawing dashed lines in Scriptable.'),
communityItem('England Bridge Status','travel','mvan231','🌉','https://raw.githubusercontent.com/mvan231/Scriptable/main/England%20Bridge%20Status.js','England Bridge Status.js','https://github.com/mvan231/Scriptable','https://opengraph.githubassets.com/7/mvan231/Scriptable',['Travel','Status'],'Stav vybraných mostů v Anglii.','Status information for selected bridges in England.'),
communityItem('Equal Stacks','tools','mvan231','▦','https://raw.githubusercontent.com/mvan231/Scriptable/main/Equal%20Stacks%20no%20hardcode.js','Equal Stacks.js','https://github.com/mvan231/Scriptable','https://opengraph.githubassets.com/8/mvan231/Scriptable',['Layout','Developer'],'Příklad stejně širokých stacků bez hardcodování.','Equal-width stack layout example without hardcoding.'),
communityItem('MEE6 LeaderBoard','social','mvan231','🏆','https://raw.githubusercontent.com/mvan231/Scriptable/main/MEE6%20LeaderBoard%20Info.js','MEE6 LeaderBoard Info.js','https://github.com/mvan231/Scriptable','https://opengraph.githubassets.com/9/mvan231/Scriptable',['Discord','Leaderboard'],'Informace z MEE6 žebříčku Discord serveru.','MEE6 Discord server leaderboard information.'),
communityItem('Mastodon Latest','social','mvan231','🐘','https://raw.githubusercontent.com/mvan231/Scriptable/main/Mastodon%20Latest.js','Mastodon Latest.js','https://github.com/mvan231/Scriptable','https://opengraph.githubassets.com/10/mvan231/Scriptable',['Mastodon','Social'],'Nejnovější příspěvek z Mastodonu.','Latest Mastodon post.'),
communityItem('OpenWeatherMap API Example','weather','mvan231','🌦️','https://raw.githubusercontent.com/mvan231/Scriptable/main/OpenWeatherMap%20API%20Example.js','OpenWeatherMap API Example.js','https://github.com/mvan231/Scriptable','https://opengraph.githubassets.com/11/mvan231/Scriptable',['Weather','API'],'Praktický příklad použití OpenWeatherMap API.','Practical OpenWeatherMap API example.'),
communityItem('Pollen Today','health','mvan231','🌼','https://raw.githubusercontent.com/mvan231/Scriptable/main/Pollen.com%20API%20-%20Today.js','Pollen Today.js','https://github.com/mvan231/Scriptable','https://opengraph.githubassets.com/12/mvan231/Scriptable',['Pollen','Health'],'Denní přehled pylové situace.','Daily pollen conditions overview.'),
communityItem('RH Downloads','tools','mvan231','⬇️','https://raw.githubusercontent.com/mvan231/Scriptable/main/RH-Downloads.js','RH-Downloads.js','https://github.com/mvan231/Scriptable','https://opengraph.githubassets.com/13/mvan231/Scriptable',['Downloads','Tools'],'Pomocný Scriptable nástroj pro stahování.','Scriptable helper for downloads.'),
communityItem('Reminders Widget','calendar','mvan231','✅','https://raw.githubusercontent.com/mvan231/Scriptable/main/Reminders%20Widget.js','Reminders Widget.js','https://github.com/mvan231/Scriptable','https://opengraph.githubassets.com/14/mvan231/Scriptable',['Reminders','Tasks'],'Přehled úkolů z Připomínek.','Overview of tasks from Reminders.'),
communityItem('Remove Scheduled Notifications','tools','mvan231','🔕','https://raw.githubusercontent.com/mvan231/Scriptable/main/Remove%20Scheduled%20Notifications.js','Remove Scheduled Notifications.js','https://github.com/mvan231/Scriptable','https://opengraph.githubassets.com/15/mvan231/Scriptable',['Notifications','Maintenance'],'Odstranění naplánovaných notifikací.','Tool for removing scheduled notifications.'),
communityItem('ScriptBackup','tools','mvan231','💾','https://raw.githubusercontent.com/mvan231/Scriptable/main/ScriptBackup.js','ScriptBackup.js','https://github.com/mvan231/Scriptable','https://opengraph.githubassets.com/16/mvan231/Scriptable',['Backup','Scripts'],'Jednoduchá záloha Scriptable skriptů.','Simple backup for Scriptable scripts.'),
communityItem('Simple Image Widget','art','mvan231','🖼️','https://raw.githubusercontent.com/mvan231/Scriptable/main/Simple%20Image%20Widget.js','Simple Image Widget.js','https://github.com/mvan231/Scriptable','https://opengraph.githubassets.com/17/mvan231/Scriptable',['Image','Widget'],'Jednoduchý obrázkový widget.','Simple image widget.'),
communityItem('Strava API','sport','mvan231','🏃','https://raw.githubusercontent.com/mvan231/Scriptable/main/Strava/StravaAPI.js','StravaAPI.js','https://github.com/mvan231/Scriptable/tree/main/Strava','https://opengraph.githubassets.com/18/mvan231/Scriptable',['Strava','Fitness'],'Ukázka integrace Strava API.','Example Strava API integration.'),
communityItem('Transparent Stock Change','finance','mvan231','📈','https://raw.githubusercontent.com/mvan231/Scriptable/main/Transparent%20StockChange.js','Transparent StockChange.js','https://github.com/mvan231/Scriptable','https://opengraph.githubassets.com/19/mvan231/Scriptable',['Stocks','Transparent'],'Transparentní widget změny ceny akcie.','Transparent stock price-change widget.'),
communityItem('Twitter Widget','social','mvan231','🐦','https://raw.githubusercontent.com/mvan231/Scriptable/main/Twitter%20Widget.js','Twitter Widget.js','https://github.com/mvan231/Scriptable','https://opengraph.githubassets.com/20/mvan231/Scriptable',['Twitter','Social'],'Přehled obsahu z Twitteru/X.','Twitter/X content widget.'),
communityItem('Upcoming Calendar Agenda','calendar','mvan231','📋','https://raw.githubusercontent.com/mvan231/Scriptable/main/Upcoming%20Calendar%20Agenda.js','Upcoming Calendar Agenda.js','https://github.com/mvan231/Scriptable','https://opengraph.githubassets.com/21/mvan231/Scriptable',['Calendar','Agenda'],'Agenda nadcházejících kalendářních událostí.','Agenda of upcoming calendar events.'),
communityItem('Upcoming Calendar Indicator','calendar','mvan231','📅','https://raw.githubusercontent.com/mvan231/Scriptable/main/Upcoming%20Calendar%20Indicator.js','Upcoming Calendar Indicator.js','https://github.com/mvan231/Scriptable','https://opengraph.githubassets.com/22/mvan231/Scriptable',['Calendar','Indicator'],'Kompaktní indikátor dalších událostí.','Compact upcoming-event indicator.'),
communityItem('VSCO Recents','social','mvan231','📷','https://raw.githubusercontent.com/mvan231/Scriptable/main/VSCO%20Recents/VSCO%20Recents%20Widget.js','VSCO Recents Widget.js','https://github.com/mvan231/Scriptable/tree/main/VSCO%20Recents','https://opengraph.githubassets.com/23/mvan231/Scriptable',['VSCO','Photos'],'Nejnovější fotografie z VSCO profilu.','Latest photos from a VSCO profile.'),
communityItem('Weather Overview','weather','mvan231','☁️','https://raw.githubusercontent.com/mvan231/Scriptable/main/Weather%20Overview/Weather%20Overview.js','Weather Overview.js','https://github.com/mvan231/Scriptable/tree/main/Weather%20Overview','https://opengraph.githubassets.com/24/mvan231/Scriptable',['Weather','Forecast'],'Přehled počasí a předpovědi.','Weather and forecast overview.'),
communityItem('Weather Snarky','weather','mvan231','😏','https://raw.githubusercontent.com/mvan231/Scriptable/main/Weather%20Snarky.js','Weather Snarky.js','https://github.com/mvan231/Scriptable','https://opengraph.githubassets.com/25/mvan231/Scriptable',['Weather','Fun'],'Počasí podané s humornými hláškami.','Weather with humorous commentary.'),
communityItem('Exchange Rate','finance','mvan231','💱','https://raw.githubusercontent.com/mvan231/Scriptable/main/exchangeRate.js','exchangeRate.js','https://github.com/mvan231/Scriptable','https://opengraph.githubassets.com/26/mvan231/Scriptable',['Currency','Rates'],'Rychlý přehled směnného kurzu.','Quick exchange-rate overview.'),

// rushhiii — 10
communityItem('OpenWeather AQI','health','rushhiii','🌫️','https://raw.githubusercontent.com/rushhiii/Scriptable-iOSWidgets/main/Widgets/AQI%20Widget/OpenWeatherAQI.js','OpenWeatherAQI.js','https://github.com/rushhiii/Scriptable-iOSWidgets','https://raw.githubusercontent.com/rushhiii/Scriptable-iOSWidgets/main/.assets/aqi/openweatheraqi_showcase.png',['AQI','Weather'],'Kvalita ovzduší z OpenWeather ve widgetu.','OpenWeather air-quality widget.'),
communityItem('Life Progress','calendar','rushhiii','🎂','https://raw.githubusercontent.com/rushhiii/Scriptable-iOSWidgets/main/Widgets/Birthday%20Widget/HowOldmi.js','HowOldmi.js','https://github.com/rushhiii/Scriptable-iOSWidgets','https://raw.githubusercontent.com/rushhiii/Scriptable-iOSWidgets/main/.assets/birthday/birthday_showcase.png',['Birthday','Progress'],'Věk a průběh života v přehledném widgetu.','Age and life-progress widget.'),
communityItem('MyCountdowns v2','calendar','rushhiii','⏳','https://raw.githubusercontent.com/rushhiii/Scriptable-iOSWidgets/main/Widgets/Countdown%20Widget/v2/MyCountdowns-v2.js','MyCountdowns-v2.js','https://github.com/rushhiii/Scriptable-iOSWidgets','https://raw.githubusercontent.com/rushhiii/Scriptable-iOSWidgets/main/.assets/countdown/countdown_v2_showcase.png',['Countdown','Events'],'Novější verze countdown widgetu.','Newer version of the countdown widget.'),
communityItem('Notion Countdowns','calendar','rushhiii','🗂️','https://raw.githubusercontent.com/rushhiii/Scriptable-iOSWidgets/main/Widgets/Countdown%20Widget/v2/NotionCountdowns.js','NotionCountdowns.js','https://github.com/rushhiii/Scriptable-iOSWidgets','https://raw.githubusercontent.com/rushhiii/Scriptable-iOSWidgets/main/.assets/countdown/countdown_v2_showcase.png',['Notion','Countdown'],'Odpočty událostí načítané z Notion.','Event countdowns loaded from Notion.'),
communityItem('My GitHub Stats','tools','rushhiii','🐙','https://raw.githubusercontent.com/rushhiii/Scriptable-iOSWidgets/main/Widgets/GitHubStats%20Widget/MyGitHubStats.js','MyGitHubStats.js','https://github.com/rushhiii/Scriptable-iOSWidgets','https://raw.githubusercontent.com/rushhiii/Scriptable-iOSWidgets/main/.assets/githubstats/githubstats_showcase.png',['GitHub','Stats'],'Statistiky GitHub profilu na ploše.','GitHub profile statistics on the Home Screen.'),
communityItem('Hindu Color Wear','tools','rushhiii','🎨','https://raw.githubusercontent.com/rushhiii/Scriptable-iOSWidgets/main/Widgets/HinduClrWear%20Widget/WearClrAccHindu.js','WearClrAccHindu.js','https://github.com/rushhiii/Scriptable-iOSWidgets','https://raw.githubusercontent.com/rushhiii/Scriptable-iOSWidgets/main/.assets/hinduclrwear/hinduclrwear_showcase.png',['Colors','Daily'],'Denní doporučení barvy podle hinduistického kalendáře.','Daily color recommendation based on the Hindu calendar.'),
communityItem('Notion Quotes','reading','rushhiii','💬','https://raw.githubusercontent.com/rushhiii/Scriptable-iOSWidgets/main/Widgets/Quote%20Widget/NotionQuotes.js','NotionQuotes.js','https://github.com/rushhiii/Scriptable-iOSWidgets','https://raw.githubusercontent.com/rushhiii/Scriptable-iOSWidgets/main/.assets/quotes/quote_showcase.png',['Notion','Quotes'],'Citáty načítané z databáze Notion.','Quotes loaded from a Notion database.'),
communityItem('Quote Light','reading','rushhiii','✨','https://raw.githubusercontent.com/rushhiii/Scriptable-iOSWidgets/main/Widgets/Quote%20Widget/light%20version/quote.js','quote.js','https://github.com/rushhiii/Scriptable-iOSWidgets','https://raw.githubusercontent.com/rushhiii/Scriptable-iOSWidgets/main/.assets/quotes/quote_showcase.png',['Quotes','Minimal'],'Lehký minimalistický widget s citáty.','Lightweight minimalist quote widget.'),
communityItem('Modular Time Progress','tools','rushhiii','⏱️','https://raw.githubusercontent.com/rushhiii/Scriptable-iOSWidgets/main/Widgets/TimeProgress%20Widget/ModularTimeProgress.js','ModularTimeProgress.js','https://github.com/rushhiii/Scriptable-iOSWidgets','https://raw.githubusercontent.com/rushhiii/Scriptable-iOSWidgets/main/.assets/timeprogress/timeprogress_showcase.png',['Time','Progress'],'Modulární průběh dne, týdne a roku.','Modular day, week and year progress.'),
communityItem('My Toyota','cars','rushhiii','🚗','https://raw.githubusercontent.com/rushhiii/Scriptable-iOSWidgets/main/Widgets/Toyota%20Widget/MyToyota.js','MyToyota.js','https://github.com/rushhiii/Scriptable-iOSWidgets','https://raw.githubusercontent.com/rushhiii/Scriptable-iOSWidgets/main/.assets/toyota/toyota_l.png',['Toyota','Car'],'Informace o voze Toyota v Scriptable widgetu.','Toyota vehicle information widget.'),

// Nicolas-kings — 16
communityItem('ONE-Tool','tools','Nicolas-kings','🧰','https://raw.githubusercontent.com/Nicolasking007/Scriptable/main/ONE-tool/ONE-Tool.Enc.js','ONE-Tool.Enc.js','https://github.com/Nicolasking007/Scriptable','https://i.loli.net/2021/03/27/sH1AGgCmOK3ilqu.jpg',['Dashboard','Weather'],'Kombinovaný dashboard s časem, počasím a stavovými údaji.','Combined dashboard with time, weather and status data.'),
communityItem('ONE-Progress','tools','Nicolas-kings','📊','https://raw.githubusercontent.com/Nicolasking007/Scriptable/main/ONE-Progress/ONE-Progress.Enc.js','ONE-Progress.Enc.js','https://github.com/Nicolasking007/Scriptable','https://i.loli.net/2021/03/27/pz7i8DsA3WkGaTU.jpg',['Progress','Time'],'Průběh dne, týdne, měsíce, roku a života.','Progress of day, week, month, year and life.'),
communityItem('ONE-Friday','calendar','Nicolas-kings','🎉','https://raw.githubusercontent.com/Nicolasking007/Scriptable/main/ONE-Friday/ONE-Friday.Enc.js','ONE-Friday.Enc.js','https://github.com/Nicolasking007/Scriptable','https://pic.rmb.bdstatic.com/bjh/56ffd9646ed482568653f1fc543c3dda.png',['Friday','Fun'],'Jednoduchý widget odpovídající, zda je dnes pátek.','Simple widget answering whether today is Friday.'),
communityItem('ONE-Countdown','calendar','Nicolas-kings','⏳','https://raw.githubusercontent.com/Nicolasking007/Scriptable/main/ONE-cuntdown/ONE-cuntdown.Enc.js','ONE-cuntdown.Enc.js','https://github.com/Nicolasking007/Scriptable','https://i.loli.net/2021/03/27/64eOAa1FtvDBm7J.jpg',['Countdown','Events'],'Jednoduchý odpočet do vybrané události.','Simple countdown to a selected event.'),
communityItem('ONE-Hot Comments','music','Nicolas-kings','🎵','https://raw.githubusercontent.com/Nicolasking007/Scriptable/main/ONE-hotcomments/ONE-hotcomments.Enc.js','ONE-hotcomments.Enc.js','https://github.com/Nicolasking007/Scriptable','https://i.loli.net/2021/04/04/KQARiV18gzv2cDj.jpg',['Music','Comments'],'Hudební widget s populárními komentáři.','Music widget with popular comments.'),
communityItem('ONE-Oil Price','cars','Nicolas-kings','⛽','https://raw.githubusercontent.com/Nicolasking007/Scriptable/main/ONE-oilprice/ONE-oilprice.Enc.js','ONE-oilprice.Enc.js','https://github.com/Nicolasking007/Scriptable','https://i.loli.net/2021/03/27/OLpBgxMtnSJHWmh.jpg',['Fuel','Price'],'Přehled aktuálních cen paliv.','Current fuel-price overview.'),
communityItem('ONE-Today','calendar','Nicolas-kings','📅','https://raw.githubusercontent.com/Nicolasking007/Scriptable/main/ONE-Today/ONE-Today.Enc.js','ONE-Today.Enc.js','https://github.com/Nicolasking007/Scriptable','https://i.loli.net/2021/03/27/TbFJz8slCiYONV4.jpg',['Calendar','Today'],'Jednoduchý denní kalendářní widget.','Simple daily calendar widget.'),
communityItem('Shortcut Community Dashboard','tools','Nicolas-kings','⚡','https://raw.githubusercontent.com/Nicolasking007/Scriptable/main/%E6%8D%B7%E5%BE%84%E7%A4%BE%E5%8C%BA%E6%95%B0%E6%8D%AE%E7%9C%8B%E6%9D%BF/%E6%8D%B7%E5%BE%84%E7%A4%BE%E5%8C%BA%E6%95%B0%E6%8D%AE.js','Shortcut Community Dashboard.js','https://github.com/Nicolasking007/Scriptable','https://i.loli.net/2021/04/25/yJx4jGIMCRKodqg.jpg',['Shortcuts','Dashboard'],'Datový dashboard komunity Apple Shortcuts.','Apple Shortcuts community data dashboard.'),
communityItem('Shortcut Box Dashboard','tools','Nicolas-kings','📦','https://raw.githubusercontent.com/Nicolasking007/Scriptable/main/%E6%8D%B7%E5%BE%84%E7%9B%92%E6%95%B0%E6%8D%AE%E7%9C%8B%E6%9D%BF/%E6%8D%B7%E5%BE%84%E7%9B%92%E6%95%B0%E6%8D%AE.js','Shortcut Box Dashboard.js','https://github.com/Nicolasking007/Scriptable','https://i.loli.net/2021/04/25/yJx4jGIMCRKodqg.jpg',['Shortcuts','Dashboard'],'Dashboard statistik pro Shortcuts katalog.','Statistics dashboard for a Shortcuts catalog.'),
communityItem('ONE-Memorandum','calendar','Nicolas-kings','🗒️','https://raw.githubusercontent.com/Nicolasking007/Scriptable/main/ONE-memorandum/ONE-memorandum.Enc.js','ONE-memorandum.Enc.js','https://github.com/Nicolasking007/Scriptable','https://i.loli.net/2021/05/31/anHWT9g6Bzmxoi7.jpg',['Calendar','Wallpaper'],'Kalendářně laděný informační widget.','Calendar-styled information widget.'),
communityItem('ONE-NBAMATCH','sport','Nicolas-kings','🏀','https://raw.githubusercontent.com/Nicolasking007/Scriptable/main/ONE-NBAMATCH/ONE-NBAMATCH.Enc.js','ONE-NBAMATCH.Enc.js','https://github.com/Nicolasking007/Scriptable','https://i.loli.net/2021/06/04/ietfW3wKngVLBGX.jpg',['NBA','Scores'],'Výsledky a zápasy oblíbeného NBA týmu.','Results and games for a favorite NBA team.'),
communityItem('ONE-LOLMATCH','gaming','Nicolas-kings','🎮','https://raw.githubusercontent.com/Nicolasking007/Scriptable/main/ONE-LOLMATCH/ONE-LOLMATCH.Enc.js','ONE-LOLMATCH.Enc.js','https://github.com/Nicolasking007/Scriptable','https://i.loli.net/2021/06/13/Uknrwv8LPTZEAmK.jpg',['League of Legends','Esports'],'Výsledky a program vybraného LPL týmu.','Results and schedule for a selected LPL team.'),
communityItem('ONE-FOOTMATCH','sport','Nicolas-kings','⚽','https://raw.githubusercontent.com/Nicolasking007/Scriptable/main/ONE-FOOTMATCH/ONE-FOOTMATCH.Enc.js','ONE-FOOTMATCH.Enc.js','https://github.com/Nicolasking007/Scriptable','https://i.loli.net/2021/06/13/6B3sTjg8VwaRGmP.jpg',['Football','Scores'],'Fotbalové zápasy a výsledky ve widgetu.','Football matches and results in a widget.'),
communityItem('ONE-Olympic','sport','Nicolas-kings','🥇','https://raw.githubusercontent.com/Nicolasking007/Scriptable/main/ONE-Olympic/ONE-Olympic.Enc.js','ONE-Olympic.Enc.js','https://github.com/Nicolasking007/Scriptable','https://i.loli.net/2021/07/24/sfr1aeEKlyRnIu4.jpg',['Olympics','Medals'],'Olympijská medailová tabulka ve widgetu.','Olympic medal table widget.'),
communityItem('ONE-Forwardtime','tools','Nicolas-kings','⏱️','https://raw.githubusercontent.com/Nicolasking007/Scriptable/main/ONE-Forwardtime/ONE-Forwardtime.Enc.js','ONE-Forwardtime.Enc.js','https://github.com/Nicolasking007/Scriptable','https://pic.rmb.bdstatic.com/bjh/d2fd42a569bef6049a1835c14051c6b8.jpeg',['Timer','Progress'],'Počítání času od zvoleného okamžiku.','Counts time forward from a chosen moment.'),
communityItem('ONE-DayMatter','calendar','Nicolas-kings','📆','https://raw.githubusercontent.com/Nicolasking007/Scriptable/main/ONE-DayMatter/ONE-DayMatter.Enc.js','ONE-DayMatter.Enc.js','https://github.com/Nicolasking007/Scriptable','https://z1.ax1x.com/2023/09/17/pPhEIO0.jpg',['Countdown','Lock Screen'],'Odpočet dnů a kalendář pro zamykací obrazovku.','Day countdown and Lock Screen calendar.'),

// marcjulianschwarz — 5
communityItem('Boca Chica SpaceX','space','marcjulianschwarz','🚀','https://raw.githubusercontent.com/marcjulianschwarz/scriptable-widgets/main/boca-chica-spacex/boca-chica-spacex.js','boca-chica-spacex.js','https://github.com/marcjulianschwarz/scriptable-widgets/tree/main/boca-chica-spacex','https://raw.githubusercontent.com/marcjulianschwarz/scriptable-widgets/main/boca-chica-spacex/images/IMG_2323.jpg',['SpaceX','Space'],'Přehled informací z Boca Chica / SpaceX.','Boca Chica / SpaceX information widget.'),
communityItem('Germany Rain Radar','weather','marcjulianschwarz','🌧️','https://raw.githubusercontent.com/marcjulianschwarz/scriptable-widgets/main/germany-rain-radar/germany-rain-radar.js','germany-rain-radar.js','https://github.com/marcjulianschwarz/scriptable-widgets/tree/main/germany-rain-radar','https://raw.githubusercontent.com/marcjulianschwarz/scriptable-widgets/main/germany-rain-radar/images/IMG_1563.jpg',['Rain','Radar'],'Dešťový radar pro Německo.','Rain radar widget for Germany.'),
communityItem('NASA Pictures','space','marcjulianschwarz','🌌','https://raw.githubusercontent.com/marcjulianschwarz/scriptable-widgets/main/nasa-pictures/nasa-pictures.js','nasa-pictures.js','https://github.com/marcjulianschwarz/scriptable-widgets/tree/main/nasa-pictures','https://raw.githubusercontent.com/marcjulianschwarz/scriptable-widgets/main/nasa-pictures/images/IMG_1652.jpg',['NASA','Photos'],'Vesmírné fotografie NASA ve widgetu.','NASA space pictures in a widget.'),
communityItem('Newsroom','news','marcjulianschwarz','📰','https://raw.githubusercontent.com/marcjulianschwarz/scriptable-widgets/main/newsroom/newsroom.js','newsroom.js','https://github.com/marcjulianschwarz/scriptable-widgets/tree/main/newsroom','https://raw.githubusercontent.com/marcjulianschwarz/scriptable-widgets/main/newsroom/images/IMG_2361.jpg',['News','Feeds'],'Minimalistický přehled zpráv.','Minimal news overview widget.'),
communityItem('Telekom Data Usage','mobile','marcjulianschwarz','📶','https://raw.githubusercontent.com/marcjulianschwarz/scriptable-widgets/main/telekom-data-usage/telekom-data-usage.js','telekom-data-usage.js','https://github.com/marcjulianschwarz/scriptable-widgets/tree/main/telekom-data-usage','https://opengraph.githubassets.com/1/marcjulianschwarz/scriptable-widgets',['Telekom','Data'],'Přehled využití mobilních dat Telekom.','Telekom mobile-data usage overview.'),

// Popular standalone projects — 13
communityItem('Weather-Cal','weather','mzeryck','🌤️','https://raw.githubusercontent.com/mzeryck/Weather-Cal/main/weather-cal.js','weather-cal.js','https://github.com/mzeryck/Weather-Cal','https://opengraph.githubassets.com/1/mzeryck/Weather-Cal',['Weather','Calendar'],'Jeden z nejznámějších Scriptable widgetů kombinující počasí, kalendář a další moduly.','One of the best-known Scriptable widgets combining weather, calendar and modules.'),
communityItem('Widget Blur','art','mzeryck','🫧','https://raw.githubusercontent.com/mzeryck/Widget-Blur/main/widget-blur.js','widget-blur.js','https://github.com/mzeryck/Widget-Blur','https://raw.githubusercontent.com/mzeryck/Widget-Blur/main/measurements.png',['Blur','Transparent'],'Nástroj pro vytvoření rozmazaného nebo transparentního pozadí widgetu.','Tool for blurred or transparent widget backgrounds.'),
communityItem('Conversable','social','andyngo','💬','https://raw.githubusercontent.com/andyngo/conversable-for-scriptable/main/Conversable.js','Conversable.js','https://github.com/andyngo/conversable-for-scriptable','https://raw.githubusercontent.com/andyngo/conversable-for-scriptable/main/conversable.png',['Messages','Contacts'],'Konverzačně laděný widget pro rychlý kontakt s lidmi.','Conversation-style widget for quick contact with people.'),
communityItem('Pocket Widget','reading','brianseidman','📚','https://raw.githubusercontent.com/brianseidman/scriptable-pocket-widget/main/pocket_widget.js','pocket_widget.js','https://github.com/brianseidman/scriptable-pocket-widget','https://raw.githubusercontent.com/brianseidman/scriptable-pocket-widget/main/Resources/scriptable-pocket-widget-image.png',['Pocket','Reading'],'Články uložené v Pocket přímo na ploše.','Pocket saved articles on the Home Screen.'),
communityItem('Steam Profile Widget','gaming','SolsticeLeaf','🎮','https://raw.githubusercontent.com/SolsticeLeaf/Scriptable-Steam-Widget/master/widget.js','SteamProfileWidget.js','https://github.com/SolsticeLeaf/Scriptable-Steam-Widget','https://opengraph.githubassets.com/1/SolsticeLeaf/Scriptable-Steam-Widget',['Steam','Gaming'],'Steam profil a herní stav ve widgetu.','Steam profile and gaming status widget.'),
communityItem('Instagram Latest Post','social','supermamon','📸','https://raw.githubusercontent.com/supermamon/scriptable-instagram-widgets/master/ig-latest-post.js','ig-latest-post.js','https://github.com/supermamon/scriptable-instagram-widgets','https://raw.githubusercontent.com/supermamon/scriptable-instagram-widgets/master/preview-igl.jpg',['Instagram','Photos'],'Nejnovější příspěvek z vybraného Instagram profilu.','Latest post from a selected Instagram profile.'),
communityItem('NHL My Team','sport','thisisevanfox','🏒','https://raw.githubusercontent.com/thisisevanfox/nhl-my-team-ios-widget/main/NHL-MyTeam-Widget.js','NHL-MyTeam-Widget.js','https://github.com/thisisevanfox/nhl-my-team-ios-widget','https://opengraph.githubassets.com/1/thisisevanfox/nhl-my-team-ios-widget',['NHL','Hockey'],'Program, výsledky a informace o oblíbeném NHL týmu.','Schedule, results and information for a favorite NHL team.'),
communityItem('NBA My Team','sport','thisisevanfox','🏀','https://raw.githubusercontent.com/thisisevanfox/nba-my-team-ios-widget/main/NBA-MyTeam-Widget.js','NBA-MyTeam-Widget.js','https://github.com/thisisevanfox/nba-my-team-ios-widget','https://opengraph.githubassets.com/1/thisisevanfox/nba-my-team-ios-widget',['NBA','Basketball'],'Program, výsledky a informace o oblíbeném NBA týmu.','Schedule, results and information for a favorite NBA team.'),
communityItem('Polestar Medium Widget','cars','niklasvieth','🚙','https://raw.githubusercontent.com/niklasvieth/polestar-ios-medium-widget/main/polestar-medium-widget.js','polestar-medium-widget.js','https://github.com/niklasvieth/polestar-ios-medium-widget','https://opengraph.githubassets.com/1/niklasvieth/polestar-ios-medium-widget',['Polestar','EV'],'Stav vozu Polestar v Medium widgetu.','Polestar vehicle status in a Medium widget.'),
communityItem('Lockscreen RSS','news','leon47331','📰','https://raw.githubusercontent.com/leon47331/scriptable-lockscreen-rss-widget/main/lockscreen-rss-widget_rotation.js','lockscreen-rss-widget_rotation.js','https://github.com/leon47331/scriptable-lockscreen-rss-widget','https://opengraph.githubassets.com/1/leon47331/scriptable-lockscreen-rss-widget',['RSS','Lock Screen'],'Rotující RSS zprávy na zamykací obrazovce.','Rotating RSS headlines on the Lock Screen.'),
communityItem('Pixel Widget','tools','unvsDev','📱','https://raw.githubusercontent.com/unvsDev/pixel-widget/main/Pixel%20Widget.js','Pixel Widget.js','https://github.com/unvsDev/pixel-widget','https://opengraph.githubassets.com/1/unvsDev/pixel-widget',['Pixel','Google'],'Widget inspirovaný vzhledem Google Pixel.','Google Pixel-inspired Scriptable widget.'),
communityItem('FordPass Widget','cars','dschablowsky','🚘','https://raw.githubusercontent.com/dschablowsky/FordPassWidget/master/Ford.js','Ford.js','https://github.com/dschablowsky/FordPassWidget','https://raw.githubusercontent.com/dschablowsky/FordPassWidget/master/fp-widget.jpg',['Ford','Car'],'Stav a informace o vozu Ford přes FordPass.','Ford vehicle status and information via FordPass.'),
communityItem('TeslaData Widget','cars','DrieStone','⚡','https://raw.githubusercontent.com/DrieStone/TeslaData-Widget/main/TeslaData%20Widget.js','TeslaData Widget.js','https://github.com/DrieStone/TeslaData-Widget','https://opengraph.githubassets.com/1/DrieStone/TeslaData-Widget',['Tesla','EV'],'Stav a vybraná data vozu Tesla ve widgetu.','Tesla vehicle status and selected data in a widget.')
];
